
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Mobile {
    private String name;
    private String color;
    private String brand;

    public Mobile(String name, String color, String brand) {
        this.name = name;
        this.color = color;
        this.brand = brand;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getColor() {
        return color;
    }

    public void setColor(String color) {
        this.color = color;
    }

    public String getBrand() {
        return brand;
    }

    public void setBrand(String brand) {
        this.brand = brand;
    }

    public void makeACall(String message){
        System.out.printf("Message : %s\n", message);
    }

    public void getBasicInfo(){
        System.out.printf("name: %s, color: %s, brand: %s\n", this.name, this.color, this.brand);
    }
}